### ISSUE TITLE
Error in transformRedditGraph2NPZ.py

### ISSUE THREAD

**Issue by xz-keg** [matenure/FastGCN#17]
I download the reddit data from snap and unzip it, and run  

> python transformRedditGraph2NPZ.py

Then it shows the following error message.

> Traceback (most recent call last): 
> File "transformRedditGraph2NPZ.py", line 69, in <module>
>     transferRedditDataFormat("reddit","reddit.npz")
>   File "transformRedditGraph2NPZ.py", line 46, in transferRedditDataFormat
>     train_ids = [n for n in G.nodes() if not G.node[n]['val'] and not G.node[n]['test']]
>   File "transformRedditGraph2NPZ.py", line 46, in <listcomp>
>     train_ids = [n for n in G.nodes() if not G.node[n]['val'] and not G.node[n]['test']]
> KeyError: 'val'

Is there a bug? Or is it because of other issues?  Thanks.

**Comment by matenure** [comment]
Probably due to the data difference. There is no "val" feature in your data. 
I believe you can solve it by editing some part of the codes. Thanks.

**Comment by ZW-ZHANG** [comment]
I think this is due to networkx version and fix it by degrading to networkx 1.10.0, as mentioned in #3

**Comment by KaiHuangMO** [comment]
thanks ZW-ZHAGN

**Comment by KaiHuangMO** [comment]
If anyone directly use transformRedditGraph2NPZ.py 
feats[:, 0] = np.log(feats[:, 0] + 1.0)  should be midified
