### ISSUE TITLE
`TypeError: 633 is not JSON serializable` when calling `create_Graph_forGraphSAGE.py`

### ISSUE THREAD

**Issue by xuehui1991** [matenure/FastGCN#24]
When runing the `create_Graph_forGraphSAGE.py`, got some error as following:

```

(py27) user@machinae:/FastGCN$ python create_Graph.py
Traceback (most recent call last):
  File "create_Graph.py", line 39, in <module>
    json.dump(data,f)
  File "/miniconda3/envs/py27/lib/python2.7/json/__init__.py", line 189, in dump
    for chunk in iterable:
  File "/miniconda3/envs/py27/lib/python2.7/json/encoder.py", line 434, in _iterencode
    for chunk in _iterencode_dict(o, _current_indent_level):
  File "/miniconda3/envs/py27/lib/python2.7/json/encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "/miniconda3/envs/py27/lib/python2.7/json/encoder.py", line 332, in _iterencode_list
    for chunk in chunks:
  File "/miniconda3/envs/py27/lib/python2.7/json/encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "/miniconda3/envs/py27/lib/python2.7/json/encoder.py", line 442, in _iterencode
    o = _default(o)
  File "/miniconda3/envs/py27/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: 633 is not JSON serializable

```

could you give me some suggestions?
Thank you.

**Comment by matenure** [comment]
I am not sure of the reason. But probably the networkx version matters. The discussions in #3 may provide some useful information.
