### ISSUE TITLE
where is Reddit dataset?

### ISSUE THREAD

**Issue by SeekPoint** [matenure/FastGCN#3]

**Comment by SeekPoint** [comment]
mldl@ub1604:~/ub16_prj/FastGCN$ python train_batch_multiRank_inductive_reddit_Mixlayers_sampleA.py
Traceback (most recent call last):
  File "train_batch_multiRank_inductive_reddit_Mixlayers_sampleA.py", line 386, in <module>
    main(None)
  File "train_batch_multiRank_inductive_reddit_Mixlayers_sampleA.py", line 122, in main
    adj, features, y_train, y_val, y_test,train_index, val_index, test_index = loadRedditFromNPZ("data/")
  File "train_batch_multiRank_inductive_reddit_Mixlayers_sampleA.py", line 60, in loadRedditFromNPZ
    adj = sp.load_npz(dataset_dir+"reddit_adj.npz")
  File "/usr/local/lib/python2.7/dist-packages/scipy/sparse/_matrix_io.py", line 130, in load_npz
    with np.load(file, **PICKLE_KWARGS) as loaded:
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/npyio.py", line 372, in load
    fid = open(file, "rb")
IOError: [Errno 2] No such file or directory: 'data/reddit_adj.npz'
mldl@ub1604:~/ub16_prj/FastGCN$

**Comment by matenure** [comment]
Please check the new uploaded file "transformRedditGraph2NPZ.py"

**Comment by SeekPoint** [comment]
ub16hp@UB16HP:~/ub16_prj/FastGCN$ python transformRedditGraph2NPZ.py 
Traceback (most recent call last):
  File "transformRedditGraph2NPZ.py", line 69, in <module>
    transferRedditDataFormat("reddit","reddit.npz")
  File "transformRedditGraph2NPZ.py", line 46, in transferRedditDataFormat
    train_ids = [n for n in G.nodes() if not G.node[n]['val'] and not G.node[n]['test']]
KeyError: 'val'
ub16hp@UB16HP:~/ub16_prj/FastGCN$

**Comment by svjack** [comment]
> ub16hp@UB16HP:/ub16_prj/FastGCN$ python transformRedditGraph2NPZ.py
> Traceback (most recent call last):
> File "transformRedditGraph2NPZ.py", line 69, in 
> transferRedditDataFormat("reddit","reddit.npz")
> File "transformRedditGraph2NPZ.py", line 46, in transferRedditDataFormat
> train_ids = [n for n in G.nodes() if not G.node[n]['val'] and not G.node[n]['test']]
> KeyError: 'val'
> ub16hp@UB16HP:/ub16_prj/FastGCN$

Same Problem !

**Comment by svjack** [comment]
> ub16hp@UB16HP:/ub16_prj/FastGCN$ python transformRedditGraph2NPZ.py
> Traceback (most recent call last):
> File "transformRedditGraph2NPZ.py", line 69, in 
> transferRedditDataFormat("reddit","reddit.npz")
> File "transformRedditGraph2NPZ.py", line 46, in transferRedditDataFormat
> train_ids = [n for n in G.nodes() if not G.node[n]['val'] and not G.node[n]['test']]
> KeyError: 'val'
> ub16hp@UB16HP:/ub16_prj/FastGCN$

i calculate the node have "val" and not have in the G init by reddit-G.json
the conclusion is : Counter({1: 231443, 0: 231443})

**Comment by svjack** [comment]
> Please check the new uploaded file "transformRedditGraph2NPZ.py"

Is is appropriate to remove node without "val" attribute from graph directly ?

**Comment by Tiiiger** [comment]
Guys, I think the problem is caused by different versions of networkx. You need nextworkx<=1.11.

**Comment by cbellei** [comment]
Also, probably useful to add that it works on tensorflow 1.8.0
